name: Newman CI
on: push

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: Setup NodeJs
        uses: actions/setup-node@v2.4.1
      
      - name: Install Newman
      - run:  npm i newman
